services:
  geodb-postgis:
    container_name: postgis
    restart: unless-stopped
    build:
      context: ./db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5444:5432"
    volumes:
      - ./db/data:/data
      - ./db/scripts:/scripts
    networks:
      - geodb_network
      - wpv-network

  geodb-backend:
    container_name: geodb-backend
    restart: unless-stopped
    build:
      context: ./backend
    depends_on:
      - geodb-postgis
    volumes:
      - ./backend:/app
    environment:
      SERVER_PORT: ${SERVER_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ORS_API_KEY: ${ORS_API_KEY}
    ports:
      - "8011:8011"
    networks:
      - geodb_network
      - wpv-network

  pgadmin:
    container_name: pgadmin
    restart: unless-stopped
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - '5052:80'
    volumes:
      - /var/lib/pgadmin
    networks:
      - geodb_network

networks:
  geodb_network:
    driver: bridge
  wpv-network:
    name: wpv-shared-network
    external: true